export interface Arecepcion{
    id_acta_recepcion:string;
    num_acta_ar:string;
    fecha_ar:string;
    hora_ar:string;
    id_tipo_atencion:string;
    id_ldfe_municipio:string;
    nom_ldfe_barrio_ar:string;
    nom_ldfecalle_ar:string;
    num_ldfe_casa_ar:string;
    id_lpd_municipio:string;
    nom_ldp_barrio_ar:string;
    nom_ldp_calle_ar:string;
    nom_ldp_empresa_ar:string;
    nombre_ldp_area_ar:string;
    nom_funcionario_ar:string;
    firma_funcionario_ar:string;
    ci_funcionario_ar:string;
    nom_persona_ar:string;
    firma_persona_ar:string;
    telf_persona_ar:string;
    ci_persona_ar:string;
}