export interface Hclinica{
    id_historia_clinica:string;
    fecha_hc:string;
    hora_hc:string;
    id_especies:string;
    nom_comun_h:string;
    id_sexo:string;
    id_edad:string;
    anamnesis_hc:string;
    id_mucosas:string;
    observaciones_hc:string;
    id_revext:string;
    pruebas_complementarias_hc:string;
    diagn_presuntivo_hc:string;
    diagn_confirmado_hc:string;
    sis_nervioso_hc:string;
    sis_respiratorio_hc:string;
    temperatura_hc:string;
    frec_cardiaca_hc:string;
    peso_hc:string;
    hreposicion_hc:string;
    hmantenimiento_hc:string;
    hperdidas_hc:string;
}